# for train/test split; Oct 2022... shouldn't run again
#alice_gv-test.conllu alice_gv-train.conllu: alice_gv.conllu
#	perl ${HOME}/gaeilge/parsail/treebank/sample.pl alice_gv.conllu 50 0
#	rm -f alice_gv-dev.conllu

clean:
	rm -f alice_gv-test.conllu alice_gv-train.conllu alice_gv-dev.conllu
