# split done Oct. 2022; shouldn't run again!
#gold-test.conllu gold-train.conllu: gold.tsv
#	perl ${HOME}/gaeilge/parsail/treebank/sample.pl gold.tsv 50 0
#	rm -f gold-dev.conllu

clean:
	rm -f gold-test.conllu gold-train.conllu gold-dev.conllu
